[package]
name = "mod-template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../../crates/common" }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
