[package]
name = "mod-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full", "derive"] }
proc-macro2 = "1.0.69"
darling = "0.10.1"
