[package]
name = "mod_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
wasm_component_layer = "0.1.16"
wasmi_runtime_layer = "0.31.0"
