[package]
name = "mod_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
anyhow.workspace = true
tracing.workspace = true
wasm_component_layer.workspace = true
wasmi_runtime_layer.workspace = true
