package example:host;

world host {

    record meta {
        none: u32,
        // id: string,
        // name: string,
        // version: string,
        // author: string,
        // description: string,
    }

    import print: func(msg: string);

    export info: func() -> meta;
    export init: func();
    export update: func();
    export shutdown: func();
}
