package example:host;

world host {
    export info: func();

    // record meta {
    //     none: u32,
    //     id: string,
    //     // name: string,
    //     // version: string,
    //     // author: string,
    //     // description: string,
    // }

    // import print: func(msg: string);

    // export get-info: func() -> meta;
    // export on-init: func();
    // export on-update: func();
    // export on-shutdown: func();
}
