package example:host;

world host {
    record string-data {
        bytes: list<u8>,
        length: u32,
    }

    record meta {
        none: u32,
        id: string-data,
        // name: string,
        // version: string,
        // author: string,
        // description: string,
    }

    import print: func(msg: string);

    export info: func() -> meta;
    export init: func();
    export update: func();
    export shutdown: func();
}
