package module:guest;

interface events {
    resource data {
        constructor();

        init: func();
        update: func(delta: f32);
        shutdown: func();
    }

    info: func() -> list<string>;
}

interface log {
    log: func(message: string);
}

interface structures {
    register-structure: func(id: string, type-name: string, data: string) -> bool;
    unregister-structure: func(id: string) -> bool;
}

world module {
    import log;
    import structures;
    export events;
}
