package module:guest;

interface general {
    resource main {
        constructor();

        init: func();
        update: func(delta: f32);
        draw: func();
        shutdown: func();
    }

    info: func() -> list<string>;
}

interface utils {
    log: func(message: string);
    fatal: func(message: string);
}

interface graphics {
    draw-rect: func(x: f32, y: f32, w: f32, h: f32);
}

world main {
    import utils;
    import graphics;

    export general;
}
