[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde-wasm-bindgen = "0.4"
anyhow = { workspace = true }
wasm-bindgen = "0.2.100"
