[package]
name = "example_mod"
description = "Example Mod: An example of how to write a mod"
authors = ["Bob", "Alice"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.16.0"
